import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";
import { hashPassword } from "@/lib/auth";
import { checkRateLimit, RATE_LIMITS, getClientIp, rateLimitResponse } from "@/lib/rate-limit";
import { registroSchema } from "@/lib/validations";
import { validateBody } from "@/lib/validate";
import { verifyTurnstile } from "@/lib/turnstile";
import { sendSystemEmail } from "@/lib/system-email";
import { buildVerificationEmail } from "@/lib/verification-email";
import { countryToCurrency } from "@/lib/pricing";

// Detects the dashboard language from the browser's Accept-Language header.
// Spanish ("es", "es-ES", "es-419", …) → "es"; everything else → "en".
function langFromAcceptLanguage(header: string | null): "es" | "en" {
  const first = (header || "").split(",")[0]?.trim().toLowerCase() || "";
  return first.startsWith("es") ? "es" : "en";
}

// Derives the new company's country/currency/locale. Currency is auto-detected
// purely from the visitor's geo (GBP=UK, EUR=eurozone, USD=rest); language is
// independent (browser-detected). Spanish → es-ES; English → en-US when billed
// in USD, otherwise en-GB.
function deriveCompanyLocale(
  lang: "es" | "en",
  geoCountry: string | null
): { country: string; currencyCode: string; locale: string; nombre: string } {
  const geo = (geoCountry || "").toUpperCase();
  const currencyCode = countryToCurrency(geo);
  if (lang !== "en") {
    return { country: geo || "ES", currencyCode, locale: "es-ES", nombre: "Mi Empresa" };
  }
  return {
    country: geo || "GB",
    currencyCode,
    locale: currencyCode === "USD" ? "en-US" : "en-GB",
    nombre: "My Company",
  };
}

export async function POST(request: NextRequest) {
  // Rate limit: 3 registrations per hour per IP
  const ip = getClientIp(request);
  const limit = checkRateLimit(`registro:${ip}`, RATE_LIMITS.registro);
  if (!limit.allowed) return rateLimitResponse(limit.resetAt);

  const body = await request.json();
  const { data, error } = validateBody(registroSchema, body);
  if (error) return error;

  // Verify Turnstile (if configured)
  const captcha = await verifyTurnstile(data.turnstileToken);
  if (!captcha.success) {
    return NextResponse.json(
      { error: "Verificacion de seguridad fallida. Intenta de nuevo." },
      { status: 403 }
    );
  }

  // Check if email already exists
  const existing = await prisma.usuario.findUnique({ where: { email: data.email } });
  if (existing) {
    return NextResponse.json(
      { error: "Ya existe una cuenta con este email" },
      { status: 409 }
    );
  }

  // Language is auto-detected from the browser (Accept-Language). An explicit
  // ?lang=en (visitor came from the English marketing site) forces English;
  // otherwise we honour the browser language (es → es, anything else → en).
  const browserLang = langFromAcceptLanguage(request.headers.get("accept-language"));
  const signupLang: "es" | "en" = body?.lang === "en" ? "en" : browserLang;
  const geoCountry = request.headers.get("x-vercel-ip-country");
  const companyLocale = deriveCompanyLocale(signupLang, geoCountry);
  const empresa = await prisma.empresa.create({
    data: {
      nombre: companyLocale.nombre,
      plan: "starter",
      planStatus: "active",
      country: companyLocale.country,
      currencyCode: companyLocale.currencyCode,
      locale: companyLocale.locale,
    },
  });

  // Create user (NOT verified yet)
  const passwordHash = await hashPassword(data.password);
  const usuario = await prisma.usuario.create({
    data: {
      nombre: data.nombre,
      email: data.email,
      passwordHash,
      plan: "starter",
      empresaId: empresa.id,
      emailVerified: false,
      // verifyToken is auto-generated by @default(cuid())
    },
  });

  // Create EquipoMembro record (user is ADMIN of their own empresa)
  await prisma.equipoMembro.create({
    data: {
      empresaId: empresa.id,
      usuarioId: usuario.id,
      rol: "ADMIN",
    },
  });

  // Send verification email in the detected signup language
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://dealforge.es";
  const verifyUrl = `${baseUrl}/verificar/${usuario.verifyToken}`;
  const { subject, html } = buildVerificationEmail(signupLang, data.nombre, verifyUrl);

  await sendSystemEmail({ to: data.email, subject, html });

  // DO NOT auto-login — redirect to "check your email" page
  return NextResponse.json({
    success: true,
    needsVerification: true,
    email: data.email,
  });
}
