import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";
import { hashPassword } from "@/lib/auth";
import { checkRateLimit, RATE_LIMITS, getClientIp, rateLimitResponse } from "@/lib/rate-limit";
import { registroSchema } from "@/lib/validations";
import { validateBody } from "@/lib/validate";
import { verifyTurnstile } from "@/lib/turnstile";
import { sendSystemEmail } from "@/lib/system-email";
import { buildVerificationEmail, resolveEmailLang } from "@/lib/verification-email";
import { countryToCurrency } from "@/lib/pricing";

// Derives the new company's country/currency/locale from the signup language
// and (when available) the visitor's geo. Spanish signups → ES/EUR/es-ES.
// English signups → GB/GBP/en-GB by default, or US/USD/en-US when geo says US,
// or IE/EUR/en-GB for Ireland.
function deriveCompanyLocale(
  lang: "es" | "en",
  geoCountry: string | null
): { country: string; currencyCode: string; locale: string; nombre: string } {
  if (lang !== "en") {
    return { country: "ES", currencyCode: "EUR", locale: "es-ES", nombre: "Mi Empresa" };
  }
  const geo = (geoCountry || "").toUpperCase();
  const country = ["GB", "US", "IE"].includes(geo) ? geo : "GB";
  return {
    country,
    currencyCode: countryToCurrency(country),
    locale: country === "US" ? "en-US" : "en-GB",
    nombre: "My Company",
  };
}

export async function POST(request: NextRequest) {
  // Rate limit: 3 registrations per hour per IP
  const ip = getClientIp(request);
  const limit = checkRateLimit(`registro:${ip}`, RATE_LIMITS.registro);
  if (!limit.allowed) return rateLimitResponse(limit.resetAt);

  const body = await request.json();
  const { data, error } = validateBody(registroSchema, body);
  if (error) return error;

  // Verify Turnstile (if configured)
  const captcha = await verifyTurnstile(data.turnstileToken);
  if (!captcha.success) {
    return NextResponse.json(
      { error: "Verificacion de seguridad fallida. Intenta de nuevo." },
      { status: 403 }
    );
  }

  // Check if email already exists
  const existing = await prisma.usuario.findUnique({ where: { email: data.email } });
  if (existing) {
    return NextResponse.json(
      { error: "Ya existe una cuenta con este email" },
      { status: 409 }
    );
  }

  // Create empresa (unique per team/company), localized from the signup language
  const signupLang = resolveEmailLang(body?.lang);
  const geoCountry = request.headers.get("x-vercel-ip-country");
  const companyLocale = deriveCompanyLocale(signupLang, geoCountry);
  const empresa = await prisma.empresa.create({
    data: {
      nombre: companyLocale.nombre,
      plan: "starter",
      planStatus: "active",
      country: companyLocale.country,
      currencyCode: companyLocale.currencyCode,
      locale: companyLocale.locale,
    },
  });

  // Create user (NOT verified yet)
  const passwordHash = await hashPassword(data.password);
  const usuario = await prisma.usuario.create({
    data: {
      nombre: data.nombre,
      email: data.email,
      passwordHash,
      plan: "starter",
      empresaId: empresa.id,
      emailVerified: false,
      // verifyToken is auto-generated by @default(cuid())
    },
  });

  // Create EquipoMembro record (user is ADMIN of their own empresa)
  await prisma.equipoMembro.create({
    data: {
      empresaId: empresa.id,
      usuarioId: usuario.id,
      rol: "ADMIN",
    },
  });

  // Send verification email in the signup language
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://dealforge.es";
  const verifyUrl = `${baseUrl}/verificar/${usuario.verifyToken}`;
  const emailLang = resolveEmailLang(body?.lang);
  const { subject, html } = buildVerificationEmail(emailLang, data.nombre, verifyUrl);

  await sendSystemEmail({ to: data.email, subject, html });

  // DO NOT auto-login — redirect to "check your email" page
  return NextResponse.json({
    success: true,
    needsVerification: true,
    email: data.email,
  });
}
