import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";
import { hashPassword } from "@/lib/auth";
import { checkRateLimit, RATE_LIMITS, getClientIp, rateLimitResponse } from "@/lib/rate-limit";
import { registroSchema } from "@/lib/validations";
import { validateBody } from "@/lib/validate";
import { verifyTurnstile } from "@/lib/turnstile";
import { sendSystemEmail } from "@/lib/system-email";

export async function POST(request: NextRequest) {
  // Rate limit: 3 registrations per hour per IP
  const ip = getClientIp(request);
  const limit = checkRateLimit(`registro:${ip}`, RATE_LIMITS.registro);
  if (!limit.allowed) return rateLimitResponse(limit.resetAt);

  const body = await request.json();
  const { data, error } = validateBody(registroSchema, body);
  if (error) return error;

  // Verify Turnstile (if configured)
  const captcha = await verifyTurnstile(data.turnstileToken);
  if (!captcha.success) {
    return NextResponse.json(
      { error: "Verificacion de seguridad fallida. Intenta de nuevo." },
      { status: 403 }
    );
  }

  // Check if email already exists
  const existing = await prisma.usuario.findUnique({ where: { email: data.email } });
  if (existing) {
    return NextResponse.json(
      { error: "Ya existe una cuenta con este email" },
      { status: 409 }
    );
  }

  // Create empresa (unique per team/company)
  const empresa = await prisma.empresa.create({
    data: {
      nombre: "Mi Empresa",
      plan: "starter",
      planStatus: "active",
    },
  });

  // Create user (NOT verified yet)
  const passwordHash = await hashPassword(data.password);
  const usuario = await prisma.usuario.create({
    data: {
      nombre: data.nombre,
      email: data.email,
      passwordHash,
      plan: "starter",
      empresaId: empresa.id,
      emailVerified: false,
      // verifyToken is auto-generated by @default(cuid())
    },
  });

  // Create EquipoMembro record (user is ADMIN of their own empresa)
  await prisma.equipoMembro.create({
    data: {
      empresaId: empresa.id,
      usuarioId: usuario.id,
      rol: "ADMIN",
    },
  });

  // Send verification email
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://dealforge.es";
  const verifyUrl = `${baseUrl}/verificar/${usuario.verifyToken}`;

  await sendSystemEmail({
    to: data.email,
    subject: "Verifica tu cuenta — DealForge",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 520px; margin: 0 auto; padding: 32px 24px;">
        <div style="text-align: center; margin-bottom: 32px;">
          <img src="https://dealforge.es/logo.svg" alt="DealForge" width="48" height="48" style="border-radius: 12px;" />
        </div>
        <h1 style="font-size: 22px; font-weight: 700; color: #111827; text-align: center; margin: 0 0 8px;">
          Bienvenido a DealForge, ${data.nombre}
        </h1>
        <p style="font-size: 14px; color: #6b7280; text-align: center; margin: 0 0 32px; line-height: 1.6;">
          Solo falta un paso: confirma tu email para activar tu cuenta.
        </p>
        <div style="text-align: center; margin-bottom: 32px;">
          <a href="${verifyUrl}" style="display: inline-block; background-color: #3a9bb5; color: white; font-size: 14px; font-weight: 600; text-decoration: none; padding: 14px 32px; border-radius: 12px;">
            Verificar mi email
          </a>
        </div>
        <p style="font-size: 12px; color: #9ca3af; text-align: center; line-height: 1.5;">
          Si no has creado una cuenta en DealForge, ignora este email.<br />
          El enlace expira en 24 horas.
        </p>
        <hr style="border: none; border-top: 1px solid #f3f4f6; margin: 24px 0;" />
        <p style="font-size: 11px; color: #d1d5db; text-align: center;">
          DealForge — CPQ Inteligente con IA para PYMEs
        </p>
      </div>
    `,
  });

  // DO NOT auto-login — redirect to "check your email" page
  return NextResponse.json({
    success: true,
    needsVerification: true,
    email: data.email,
  });
}
